name: PR Checks

on: [pull_request]

jobs:
  danger:
    name: Danger (Xcode ${{ matrix.xcode }})
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Danger
    strategy:
      matrix:
        xcode:
          - "13.2.1"
    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Setup Node.js ${{ steps.node-version.outputs.version }}
        uses: actions/setup-node@v2
        with:
          node-version-file: "Danger/.node-version"
          cache: "npm"
          cache-dependency-path: "Danger/package-lock.json"

      - run: npm ci

      - name: Build Danger and Danger Dependencies
        run: swift build --target DangerDependencies

      - name: Run Danger
        run: swift run danger-swift ci --cwd ../ --danger-js-path $(npm bin)/danger --failOnErrors --use-github-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pod_lib_lint:
    name: pod lib lint
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - "13.2.1"
    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: pod lib lint
        run: bundle exec pod lib lint
