name: PR Checks

on: [pull_request]

jobs:
  danger:
    name: Danger
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.16.3'
    - name: yarn install
      run: yarn install
    - name: Build CI Dependencies
      run: swift build --skip-update --target CIDependencies
    - name: Build danger-swift
      run: swift build --skip-update --product danger-swift
    - name: Run Danger
      run: swift run --skip-update danger-swift ci --danger-js-path $(yarn bin danger) --verbose

  pod_lib_lint:
    name: pod lib lint
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'
    - name: bundle install
      run: bundle install --deployment
    - name: pod lib lint
      run: bundle exec pod lib lint
